import{z}from'zod';
const minute=(h:string)=>Number(h.slice(0,2))*60+Number(h.slice(3,5));
export async function publicBooking(ctx:any,input:any){
 const slug=z.string().min(2).max(80).parse(input.slug);
 const clinic=(await ctx.sql.sql("SELECT id,nome,slug,telefone,cor_primaria,logo_url FROM clinica WHERE slug=? AND status!='bloqueado' AND status_cobranca!='suspenso' AND (status!='trial' OR trial_ate IS NULL OR trial_ate>=date('now'))",[slug])).rows[0];if(!clinic)throw Error('Agendamento indisponível para esta clínica');
 if(input.action==='catalog')return{clinica:clinic,profs:(await ctx.sql.sql('SELECT id,nome,especialidade,foto_url FROM profissional WHERE clinica_id=? AND ativo=1',[clinic.id])).rows,procs:(await ctx.sql.sql('SELECT id,nome,descricao,valor,duracao_minutos FROM procedimento WHERE clinica_id=? AND ativo=1',[clinic.id])).rows};
 const d=z.object({profissional_id:z.string().min(1).max(100),procedimento_id:z.string().min(1).max(100),data:z.string().regex(/^\d{4}-\d{2}-\d{2}$/)}).parse(input);
 const prof=(await ctx.sql.sql('SELECT id,nome FROM profissional WHERE id=? AND clinica_id=? AND ativo=1',[d.profissional_id,clinic.id])).rows[0];const proc=(await ctx.sql.sql('SELECT id,nome,valor,duracao_minutos FROM procedimento WHERE id=? AND clinica_id=? AND ativo=1',[d.procedimento_id,clinic.id])).rows[0];if(!prof||!proc)throw Error('Profissional ou procedimento indisponível');
 const date=new Date(d.data+'T12:00:00-03:00');if(!Number.isFinite(+date)||date.toISOString().slice(0,10)!==d.data||d.data<new Date().toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'})||+date>Date.now()+366*86400000)throw Error('Data inválida');
 const duration=Number(proc.duracao_minutos),busy=(await ctx.sql.sql("SELECT hora,duracao_minutos FROM consulta WHERE clinica_id=? AND profissional_id=? AND data=? AND status NOT IN ('cancelada','faltou')",[clinic.id,prof.id,d.data])).rows;
 const slots:string[]=[];for(let m=480;m<1080;m+=30){if(!((m<720&&m+duration<=720)||(m>=840&&m+duration<=1080)))continue;const h=String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0');if(+new Date(d.data+'T'+h+':00-03:00')<=Date.now())continue;if(!busy.some((b:any)=>minute(b.hora)<m+duration&&minute(b.hora)+Number(b.duracao_minutos)>m))slots.push(h)}
 if(input.action==='slots')return{slots};if(input.action!=='book')throw Error('Ação inválida');
 const info=z.object({nome:z.string().trim().min(2).max(150),telefone:z.string().regex(/^[+\d()\s-]{10,25}$/),email:z.union([z.literal(''),z.string().email().max(255)]).optional(),hora:z.string().regex(/^\d{2}:\d{2}$/),data_nascimento:z.string().max(10).optional(),convenio:z.string().max(150).optional()}).parse(input);if(!slots.includes(info.hora))throw Error('Horário indisponível. Escolha outro horário.');
 const pid=crypto.randomUUID(),id=crypto.randomUUID();await ctx.sql.batch([{sql:'INSERT INTO paciente(id,clinica_id,nome,telefone,email,data_nascimento,convenio) VALUES(?,?,?,?,?,?,?)',args:[pid,clinic.id,info.nome,info.telefone,info.email||null,info.data_nascimento||null,info.convenio||null]},{sql:'INSERT INTO consulta(id,clinica_id,paciente_id,paciente_nome,profissional_id,profissional_nome,data,hora,duracao_minutos,valor_total,procedimentos) VALUES(?,?,?,?,?,?,?,?,?,?,?)',args:[id,clinic.id,pid,info.nome,prof.id,prof.nome,d.data,info.hora,duration,Number(proc.valor),JSON.stringify([{id:proc.id,nome:proc.nome,valor:Number(proc.valor)}])]}],'write');
 return{ok:true,protocolo:id};
}
