import{test}from'node:test';import assert from'node:assert/strict';import{DatabaseSync}from'node:sqlite';import fs from'node:fs';import{Database,budgetTotals}from'../server/native/database';import{createClinic}from'../server/native/clinic';import{publicBooking}from'../server/native/public-booking';import{ownerEligible}from'../server/native/owner';
function fixture(){const db=new DatabaseSync(':memory:');db.exec(fs.readFileSync('scripts/native/schema.sql','utf8'));db.exec(fs.readFileSync('scripts/native/bootstrap.sql','utf8'));const sql={async sql(q:string,args:any[]=[]){return{rows:db.prepare(q).all(...args)}},async batch(ops:any[]){db.exec('BEGIN');try{const results=ops.map(o=>({rows:db.prepare(o.sql).all(...(o.args||[]))}));db.exec('COMMIT');return{results}}catch(e){db.exec('ROLLBACK');throw e}}};const ctx={sql,identity:{userId:'u1',email:'owner@example.com',master:true,clinicaId:undefined as string|undefined}};return{db,sql,ctx}}
async function seed(){const f=fixture();const a=await createClinic(f.ctx,{nome:'Clínica Teste A',email_admin:'owner@example.com',nome_admin:'Owner A',profissionais:[{nome:'Profissional A'}],procedimentos:[{nome:'Consulta A',valor:150,duracao_minutos:60}]},true);const b=await createClinic(f.ctx,{nome:'Clínica Teste B',email_admin:'other@example.com',nome_admin:'Owner B'},true);const prof=f.db.prepare('SELECT id FROM profissional WHERE clinica_id=?').get(a.id) as any;const proc=f.db.prepare('SELECT id FROM procedimento WHERE clinica_id=?').get(a.id) as any;f.db.exec(`INSERT INTO paciente(id,clinica_id,nome) VALUES('pa','${a.id}','Paciente A'),('pb','${b.id}','Paciente B');`);const user=new Database(f.sql,{userId:'u1',email:'owner@example.com',master:false,role:'owner',clinicaId:a.id});return{...f,a,b,prof,proc,user}}
test('cada clínica enxerga somente seus pacientes',async()=>{const f=await seed();const r=await f.user.from('paciente').select('*');assert.equal(r.data.length,1);assert.equal(r.data[0].id,'pa');assert.equal((await f.user.from('paciente').update({nome:'Invadido'}).eq('id','pb')).count,0)});
test('anônimo não lê dados clínicos',async()=>{const f=await seed();const r=await new Database(f.sql,{userId:'',master:false}).from('paciente').select('*');assert.match(r.error.message,/Autenticação/)});
test('referências entre clínicas são rejeitadas inclusive no banco',async()=>{const f=await seed();const r=await f.user.from('tratamento').insert({clinica_id:f.a.id,paciente_id:'pb',descricao:'X'});assert.match(r.error.message,/Referência/)});
test('recepcionista não muda financeiro nem administrador',async()=>{const f=await seed();const u=new Database(f.sql,{userId:'r',master:false,role:'recepcionista',clinicaId:f.a.id});assert.ok((await u.from('financeiro').insert({descricao:'x',valor:10,data:'2026-01-01'})).error);assert.ok((await u.from('membro_equipe').insert({email:'x@example.com',nome:'X',role:'admin'})).error)});
test('proprietário da clínica não altera cobrança ou se promove a Master',async()=>{const f=await seed();assert.ok((await f.user.from('clinica').update({status_cobranca:'ativo',valor_mensal:0}).eq('id',f.a.id)).error);assert.ok((await f.user.from('user_roles').insert({user_id:'u1',role:'super_admin'})).error)});
test('cadastro de equipe não aceita user_id arbitrário nem segundo owner',async()=>{const f=await seed();for(const p of [{role:'owner'},{user_id:'u1'}])assert.ok((await f.user.from('membro_equipe').insert({nome:'X',email:'new@example.com',...p})).error)});
test('aprovação cria um tratamento e um financeiro; repetição é idempotente',async()=>{const f=await seed();const r=await f.user.from('orcamento').insert({paciente_id:'pa',data:'2026-09-17',itens:[{nome:'Item',qtd:3,valor:10.1}],desconto_pct:10,total:99999,total_com_desconto:99999}).select('*').single();assert.equal(r.error,null);assert.equal(r.data.total,30.3);assert.equal(r.data.total_com_desconto,27.27);for(let n=0;n<2;n++)assert.equal((await f.user.from('orcamento').update({status:'aprovado'}).eq('id',r.data.id)).error,null);assert.equal(f.db.prepare('SELECT count(*) n FROM financeiro').get()?.n,1);assert.equal(f.db.prepare('SELECT valor FROM financeiro').get()?.valor,27.27);assert.equal(f.db.prepare('SELECT count(*) n FROM tratamento').get()?.n,1);assert.ok((await f.user.from('orcamento').update({desconto_pct:50}).eq('id',r.data.id)).error)});
test('falha no financeiro reverte aprovação e tratamento na mesma transação',async()=>{const f=await seed();const r=await f.user.from('orcamento').insert({paciente_id:'pa',data:'2026-09-17',itens:[{nome:'Item',qtd:1,valor:100}]}).single();f.db.exec("CREATE TRIGGER fail_finance BEFORE INSERT ON financeiro BEGIN SELECT RAISE(ABORT,'Falha de teste'); END;");assert.ok((await f.user.from('orcamento').update({status:'aprovado'}).eq('id',r.data.id)).error);assert.equal(f.db.prepare('SELECT status FROM orcamento').get()?.status,'pendente');assert.equal(f.db.prepare('SELECT count(*) n FROM tratamento').get()?.n,0)});
test('valores monetários e descontos inválidos são rejeitados',()=>{for(const d of [-1,101,NaN])assert.throws(()=>budgetTotals([{nome:'x',qtd:1,valor:100}],d));assert.throws(()=>budgetTotals([{nome:'x',qtd:0,valor:100}],0))});
test('cadastro de clínica é atômico, inclusive convites duplicados',async()=>{const f=fixture();await assert.rejects(()=>createClinic(f.ctx,{nome:'Teste',membros:[{nome:'A A',email:'owner@example.com',role:'admin'}]}));assert.equal(f.db.prepare('SELECT count(*) n FROM clinica').get()?.n,0)});
test('agendamento público usa preço e duração do servidor e não expõe pacientes',async()=>{const f=await seed();const data=new Date(Date.now()+7*86400000).toISOString().slice(0,10);const base={slug:f.a.slug,data,profissional_id:f.prof.id,procedimento_id:f.proc.id};const catalog=await publicBooking(f.ctx,{slug:f.a.slug,action:'catalog'});assert.equal(catalog.clinica.owner_email,undefined);const r=await publicBooking(f.ctx,{...base,action:'book',hora:'09:00',nome:'Paciente Teste',telefone:'11999999999',valor:0,duracao_minutos:1});assert.ok(r.protocolo);const booked=f.db.prepare('SELECT valor_total,duracao_minutos FROM consulta').get();assert.equal(booked?.valor_total,150);assert.equal(booked?.duracao_minutos,60);const before=f.db.prepare('SELECT count(*) n FROM paciente').get()?.n;await assert.rejects(()=>publicBooking(f.ctx,{...base,action:'book',hora:'09:30',nome:'Paciente Teste',telefone:'11999999999'}),/indisponível/);assert.equal(f.db.prepare('SELECT count(*) n FROM paciente').get()?.n,before);assert.ok(!(await publicBooking(f.ctx,{...base,action:'slots'})).slots.includes('09:30'))});
test('agendamento de outra clínica, passado e horário fora da jornada são rejeitados',async()=>{const f=await seed();await assert.rejects(()=>publicBooking(f.ctx,{action:'slots',slug:f.b.slug,profissional_id:f.prof.id,procedimento_id:f.proc.id,data:'2026-01-01'}));await assert.rejects(()=>publicBooking(f.ctx,{action:'slots',slug:f.a.slug,profissional_id:f.prof.id,procedimento_id:f.proc.id,data:'2000-01-01'}),/Data inválida/)});
test('primeiro visitante nunca vira Master e email precisa estar verificado',async()=>{const no= {sql:async()=>({rows:[]})};assert.equal(await ownerEligible({userId:'x',email:'x@example.com'},{BLINK_PROJECT_ID:'p',OWNER_PROJECT_ID:'p'},no),false);assert.equal(await ownerEligible({userId:'x',email:'x@example.com'},{BLINK_PROJECT_ID:'p',OWNER_PROJECT_ID:'p',OWNER_EMAIL:'x@example.com'},no),false);const yes={sql:async()=>({rows:[{email:'x@example.com',email_verified:1}]})};assert.equal(await ownerEligible({userId:'x',email:'x@example.com'},{BLINK_PROJECT_ID:'p',OWNER_PROJECT_ID:'other',OWNER_EMAIL:'x@example.com'},yes),false);assert.equal(await ownerEligible({userId:'x',email:'x@example.com'},{BLINK_PROJECT_ID:'p',OWNER_PROJECT_ID:'p',OWNER_EMAIL:'x@example.com'},yes),true)});
